name: CI

on:
  pull_request: {}
  push:
    branches: [ master ]

jobs:
  build-c:
    name: C
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: c

    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3

      - name: Builds C implementation
        run: make

  build-hs:
    name: Haskell
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: haskell

    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Haskell & Stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: latest
          stack-no-global: true

      - name: Cache ~/.stack
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: stack-global-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            stack-global-

      - name: Cache .stack-work
        uses: actions/cache@v3
        with:
          path: haskell/.stack-work
          key: stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            stack-work-

      - name: Build, test and generate coverage report
        run: stack test --coverage

      - name: Run example (e2e?) tests
        run: ./test/bats/bin/bats ./test/haskell.bats
        working-directory: .
