name: CI

on:
  pull_request: {}
  push:
    branches: [ master ]

jobs:
  build-c:
    name: C
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: c

    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3

      - name: Builds C implementation
        run: make

  build-hs:
    name: Haskell
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: haskell

    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Haskell & Stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: latest
          stack-no-global: true

      - name: Build Haskell implementation
        run: stack build

      - name: Run unit tests
        run: stack test

      - name: Run example (e2e?) tests
        run: ./test/bats/bin/bats ./test/haskell.bats
        working-directory: .
